### ISSUE TITLE
你好，请问可以参考一下您的数据库设计吗？

### ISSUE THREAD

**Issue by wxy123456qwer** [GiggleWang/web-bookstore-backend#1]

**Comment by GiggleWang** [comment]
你好👋
data文件刚刚上传到地址https://github.com/GiggleWang/web-bookstore-backend/tree/master/data
因为最后一次迭代没传data，所以可能会有一些问题，如果存在，欢迎指出，谢谢！

**Comment by wxy123456qwer** [comment]
非常感谢！：）
